spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/sampledb
    username: sa
    password: 6h5g4f#D@S!A
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        #show_sql: true
        format_sql: true

logging:
  level:
    org.hibernate.sql: debug
    org.hibernate.type: trace